sudo: required
dist: trusty

addons:
  chrome: stable
  sonarcloud:
    organization: "youtaite-collab"

matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.0.0
      install:
        - dotnet restore
      script:
        - dotnet build --no-restore
        - dotnet test --no-build Collab.API.Tests

    - language: node_js
      node_js:
        - "8.9.4"
      cache:
        directories:
          - "node_modules"
      before_script:
        - cd Collab.Interface
        - npm install -g @angular/cli
        - npm install
      script:
        - ng build
        - ng test