sudo: required
dist: trusty

addons:
  chrome: stable
  sonarcloud:
    organization: "youtaite-collab"

matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.0.0
      before_script:
        - sudo apt-get -qq update
        - mkdir tools
        - wget -O sonar.zip https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.2.0.1214/sonar-scanner-msbuild-4.2.0.1214-netcoreapp2.0.zip
        - unzip -qq sonar.zip -d tools/sonar
        - ls -l tools/sonar
        - chmod +x tools/sonar/sonar-scanner-3.1.0.1141/bin/sonar-scanner
        - chmod +x tools/sonar/SonarScanner.MSBuild.dll
      install:
        - dotnet restore
      script:
        - dotnet tools/sonar/SonarScanner.MSBuild.dll begin /k:youtaite-collab /d:sonar.login=${SONAR_TOKEN} /d:sonar.host.url="https://sonarcloud.io" /d:sonar.tests="Collab.API.Tests/**"
        - dotnet build --no-restore Collab.API
        - dotnet tools/sonar/SonarScanner.MSBuild.dll end /d:sonar.login=${SONAR_TOKEN}

    - language: node_js
      node_js:
        - "8.9.4"
      cache:
        directories:
          - "node_modules"
      before_script:
        - cd Collab.Interface
        - npm install -g @angular/cli
        - npm install
      script:
        - ng build
        - ng test