language: csharp
dist: trusty
mono: none
dotnet: 2.0.0

addons:
  sonarcloud:
    organization: "youtaite-collab"
    token:
      secure: "SKFR4FWC0mmJ4QHr1hf21JHwhg2Xmgbg3MmCiSR7D1FB1122K6TTf8pwRTrSEf666V07Kfllxymdvcn8WTFvRjYx3S0cZEAuyh66jroN4FvOHwHXTl94yLi9hRLEmstckAKwvKC/yyk3JRqHn3rWsGOUZdRGUaH/o5Og/ayrv8pnAQJEEacYmIILssCjAXPwKVa+x35WW7gcA/9rDc+Ia5otvdUYNCdaHqALmIEPyMy2dzR4kucfp8KwMMpISehGCkMq43qslHLzPfSu5VAsAoH8hOaRFADvHCZy2hD34ZGbVAwb+CN/abJLQb7t2DnHL26caEN35gJzfvd2R/4zFH1+2Nd9Pmz5/ifyrTgR2A2IURBv15z+mysUTdxCnn7mEFOsfZcHNFn175WwTkN2B6V7mHGNacagxJBpTdxLV9uAIor2AV+d1mGKkBYccF7xs9Uh/WAJKLHpgjlb5hNB3QWNFCktiopu2xf1g5VBhtzh1AiYNrlruzXzee82sK6wMFHZdv4iOrXJtAgwt7zkdNqahKTfP6TPZvhxxJtRWmqmrnw7M443KVvPyM99p6+WaU755Z+WZuXCiez/u6YwwGY8a2smctZEckID4vF8rfNgWu0BdXeDbCr6mQm81Qg5itlqiM3tJVsgfuLzhDq7AG7d4GPHPjg9ftW6ZWzdPfw="

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test Collab.Tests/Collab.Tests.csproj
  - sonar-scanner