sudo: required
dist: trusty

addons:
  chrome: stable
  sonarcloud:
    organization: 'youtaite-collab'

matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.0.0
      before_script:

      install:
        - dotnet restore
      script:
        - dotnet build --no-restore
        - dotnet test Collab.API.Tests/Collab.API.Tests.csproj

    - language: node_js
      node_js:
        - "8.9.4"
      cache:
        directories:
          - "node_modules"
      before_script:
        - cd Collab.Interface
        - npm install -g @angular/cli
        - npm install
      script:
        - ng build
        - ng test

    - language: csharp
      mono: latest
      before_install:
        - wget -O sonar.zip https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.2.0.1214/sonar-scanner-msbuild-4.2.0.1214-netcoreapp2.0.zip
      	- unzip -qq sonar.zip -d tools/sonar
        - ls -l tools/sonar
        - chmod +x tools/sonar/sonar-scanner-3.1.0.1141/bin/sonar-scanner
      script:
        - mono ../tools/sonar/SonarQube.Scanner.MSBuild.exe begin /k:youtaite-collab /d:sonar.login=${SONAR_TOKEN} /d:sonar.host.url="https://sonarcloud.io"
        - dotnet build
        - dotnet test Collab.API.Tests
        - mono ../tools/sonar/SonarQube.Scanner.MSBuild.exe end /d:sonar.login=${SONAR_TOKEN}