# Use docker to build the application using development config from Vagrant
#
# To connect to Vagrant box:
#   vagrant ssh
# 
# Once in vagrant:
#   cd /vagrant
#
# To build:
#   docker-compose -f docker-compose.override.dev.yml build
#
# If not in a swarm:
#   docker swarm init
#
# To deploy:
#   docker stack deploy -c docker-compose.override.dev.yml collab
#   
# To un-deploy:
#   docker stack rm collab
# 
# check logs:
#   docker stack ps collab  # check the ID for the service you want to look at
#   docker service logs <service-ID>

version: "3.6"

services:
  webapi:
    build:
      context: Collab.API
      dockerfile: Dockerfile
    image: collab-webapi:0.1.0
    ports: 
      - "9000:80"
    networks:
      - collabnetwork
    volumes:
      - /vagrant/Collab.API/appsettings.Development.json:/app/appsettings.Development.json
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  interface:
    build:
      context: Collab.Interface
      dockerfile: Dockerfile
    image: collab-interface:0.1.0
    ports:
      - "9100:4200"
    networks:
      - collabnetwork
    environment:
      - env=dev

networks:
  collabnetwork: